branch-defaults:
  main:
    environment: null
environment-defaults:
  bootstrap-your-business-with-nodejs-env:
    branch: null
    repository: null
global:
  application_name: bootstrap-your-business-with-nodejs
  default_ec2_keyname: null
  default_platform: Node.js running on 64bit Amazon Linux
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
