name: Node.js CI

on:
  push:
    branches:
    - develop

jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Terraform Format
        working-directory: infra
        run: terraform fmt

      - name: Terraform Init
        working-directory: infra
        run: terraform init -backend-config="key=state" -backend-config="region=us-west-2"
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_KEY}}

      - name: Terraform Validate
        working-directory: infra
        run: terraform validate -no-color

      - name: Brew Install aws-elasticbeanstalk
        run: brew install aws-elasticbeanstalk

      - name: Terraform Plan
        working-directory: infra
        run: |
          export $(grep -v '^#' .env.staging | xargs -0)
          terraform workspace list
          terraform workspace select staging || terraform workspace new staging
          export $(eb printenv app-staging | grep -v 'Environment Variables' | tr -d "[:blank:]")
          terraform plan -var="master_db_username=$RDS_MASTER_USERNAME" -var="master_db_password=$RDS_MASTER_PASSWORD" -var="db_instance_class=$DB_INSTANCE_CLASS"
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_KEY}}

      - name: Terraform Apply
        working-directory: infra
        run: |
          export $(grep -v '^#' .env.staging | xargs -0)
          terraform workspace list
          terraform workspace select staging || terraform workspace new staging
          export $(eb printenv app-staging | grep -v 'Environment Variables' | tr -d "[:blank:]")
          terraform apply -auto-approve -var="master_db_username=$RDS_MASTER_USERNAME" -var="master_db_password=$RDS_MASTER_PASSWORD" -var="db_instance_class=$DB_INSTANCE_CLASS"
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_KEY}}

      - name: RDS Host/Port
        working-directory: infra
        run: |
          echo $(terraform output rds_hostname)
          echo $(terraform output rds_port)
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_KEY}}

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.15.4'

      - name: Installing NPM
        run: npm install

      - name: Run tests
        run: npm run test

      - name: EB Deploy
        run: eb deploy
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_KEY}}

      - name: Deployed!
        run: echo App deployed to ELB